# Generated by Django 4.2.4 on 2024-06-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0004_chatuser_is_team_member_alter_message_user_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='email',
            field=models.EmailField(default='robelt59@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
