# Generated by Django 4.2.4 on 2024-06-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0005_room_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
