# Generated by Django 4.2.4 on 2024-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0007_room_last_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
