# Generated by Django 4.2.4 on 2024-05-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailaccess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohomailaccount',
            name='account_id',
        ),
    ]
