# Generated by Django 4.2.4 on 2024-05-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailaccess', '0002_remove_zohomailaccount_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohomailaccount',
            name='zoho_refresh_folder',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
