# Generated by Django 4.2.4 on 2024-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailaccess', '0003_zohomailaccount_zoho_refresh_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohomailaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zohomailaccount',
            name='inbox_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zohomailaccount',
            name='redirect_uri',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zohomailaccount',
            name='sent_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
