# Generated by Django 4.2.4 on 2024-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailaccess', '0004_zohomailaccount_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohomailaccount',
            name='client_id',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='zohomailaccount',
            name='client_secr',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
