# Generated by Django 4.2.4 on 2024-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailaccess', '0005_zohomailaccount_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohomailaccount',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
