# Generated by Django 4.2.4 on 2024-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailaccess', '0006_zohomailaccount_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('fromm', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
