# Generated by Django 4.2.3 on 2023-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_online_room_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
