# Generated by Django 4.2.3 on 2023-08-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_data_myimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyImageModel',
            new_name='image',
        ),
    ]
