# Generated by Django 4.2.4 on 2023-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_myimagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='simage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='simage',
            field=models.ManyToManyField(to='web.simage'),
        ),
    ]
