# Generated by Django 4.2.4 on 2023-10-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_image_height_alter_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='ip_address',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
