# Generated by Django 4.2.4 on 2023-10-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_useraccess_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='simage',
            field=models.ManyToManyField(default=None, null=True, to='web.simage'),
        ),
    ]
