# Generated by Django 4.2.4 on 2023-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simage',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
