# Generated by Django 4.2.4 on 2023-10-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_client_client_image_companycontact_fuchers_map_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmoni_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0, help_text='Width of the image in pixels')),
                ('height', models.PositiveIntegerField(default=0, help_text='Height of the image in pixels')),
            ],
        ),
        migrations.CreateModel(
            name='worker_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0, help_text='Width of the image in pixels')),
                ('height', models.PositiveIntegerField(default=0, help_text='Height of the image in pixels')),
            ],
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
