# Generated by Django 4.2.4 on 2023-12-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='galry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ManyToManyField(default=None, null=True, to='web.simage')),
            ],
        ),
    ]
