# Generated by Django 4.2.4 on 2023-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_galry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galry',
            name='image',
        ),
        migrations.AddField(
            model_name='galry',
            name='image',
            field=models.ImageField(null=True, upload_to='galry/'),
        ),
    ]
