# Generated by Django 4.2.4 on 2024-01-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_galry_image_galry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuchers',
            name='sass',
            field=models.BooleanField(default=False),
        ),
    ]
