# Generated by Django 4.2.4 on 2024-01-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_fuchers_sass'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus', models.TextField(blank=True, null=True)),
                ('ans', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
