# Generated by Django 4.2.4 on 2024-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuchers',
            name='faq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuchers',
            name='galry',
            field=models.BooleanField(default=False),
        ),
    ]
