# Generated by Django 4.2.4 on 2024-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_fuchers_faq_fuchers_galry'),
    ]

    operations = [
        migrations.CreateModel(
            name='galry_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0, help_text='Width of the image in pixels')),
                ('height', models.PositiveIntegerField(default=0, help_text='Height of the image in pixels')),
            ],
        ),
    ]
