# Generated by Django 4.2.4 on 2024-04-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_galry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='simage',
            field=models.ManyToManyField(default=None, to='web.simage'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='socilamedia_worker',
            field=models.ManyToManyField(default=None, to='web.socilamedia_worker'),
        ),
    ]
