# Generated by Django 4.2.4 on 2024-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_service_simage_alter_worker_socilamedia_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuchers',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuchers',
            name='project',
            field=models.BooleanField(default=False),
        ),
    ]
