# Generated by Django 4.2.4 on 2024-05-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_fuchers_news_fuchers_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuchers',
            name='orderservice',
            field=models.BooleanField(default=False),
        ),
    ]
