# Generated by Django 4.2.4 on 2024-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_fuchers_orderservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuchers',
            name='email',
            field=models.BooleanField(default=False),
        ),
    ]
