# Generated by Django 4.2.4 on 2024-06-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_companycontact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
