# Generated by Django 4.2.4 on 2024-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_sitestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
