# Generated by Django 4.2.4 on 2024-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_link_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmone',
            name='postion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
