# Generated by Django 4.2.4 on 2024-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_testmone_postion'),
    ]

    operations = [
        migrations.AddField(
            model_name='galry',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galry',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
