# Generated by Django 4.2.4 on 2024-08-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_galry_name_galry_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='gtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='galry',
            name='name',
        ),
        migrations.AddField(
            model_name='galry',
            name='gtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.gtype'),
        ),
    ]
