# Generated by Django 4.2.4 on 2024-08-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_gtype_remove_galry_name_galry_gtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtype',
            old_name='qus',
            new_name='name',
        ),
    ]
