# Generated by Django 4.2.4 on 2024-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_rename_qus_gtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtype',
            name='name',
            field=models.TextField(blank=True, max_length=36, null=True),
        ),
    ]
