# Generated by Django 4.2.4 on 2024-05-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contents',
        ),
    ]
