# Generated by Django 4.2.4 on 2024-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_remove_blog_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
