# Generated by Django 4.2.4 on 2024-05-20 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='content',
        ),
        migrations.RemoveField(
            model_name='codeblock',
            name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.RemoveField(
            model_name='list',
            name='content',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='content',
        ),
        migrations.RemoveField(
            model_name='title',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.AddField(
            model_name='ad',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='blogg.blog'),
        ),
        migrations.AddField(
            model_name='codeblock',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeblock', to='blogg.blog'),
        ),
        migrations.AddField(
            model_name='content',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='blogg.blog'),
        ),
        migrations.AddField(
            model_name='list',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='blogg.blog'),
        ),
        migrations.AddField(
            model_name='quote',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='blogg.blog'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='blogg.blog'),
        ),
        migrations.AddField(
            model_name='title',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titleblog', to='blogg.blog'),
        ),
        migrations.AddField(
            model_name='video',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='blogg.blog'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageblog', to='blogg.blog')),
            ],
        ),
    ]
