# Generated by Django 4.2.4 on 2024-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0005_imagecontent_imagemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
