# Generated by Django 4.2.4 on 2024-05-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blogg', '0006_blogcontent_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.contenttype'),
        ),
    ]
