# Generated by Django 4.2.4 on 2024-06-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_blog_price_order_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Service',
        ),
    ]
