# Generated by Django 4.2.4 on 2024-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_blog_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quntity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
