# Generated by Django 4.2.4 on 2023-11-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_chart_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quntity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
