# Generated by Django 4.2.4 on 2024-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_quntity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
