# Generated by Django 4.2.4 on 2024-01-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_galry_image'),
        ('shop', '0004_item_disc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='CustomUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.customuser'),
        ),
    ]
