# Generated by Django 4.2.4 on 2024-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_client_guest_email_remove_client_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='guest_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='guest_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
