# Generated by Django 4.2.4 on 2024-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
