# Generated by Django 4.2.4 on 2024-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rating_created_at_alter_rating_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
