# Generated by Django 4.2.4 on 2024-01-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_chart',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order_chart',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_chart',
            name='expird',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_chart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_chart',
            name='payid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
