# Generated by Django 4.2.4 on 2024-01-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_chart_active_order_chart_deliver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
