# Generated by Django 4.2.4 on 2024-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_bank_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='Bank_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
