# Generated by Django 4.2.4 on 2024-01-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_bank_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(null=True, upload_to='payment/'),
        ),
    ]
