# Generated by Django 4.2.4 on 2024-01-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_payment_user_payment_client_payment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
