# Generated by Django 4.2.4 on 2024-01-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_client_guest_email_alter_client_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='payment/')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='image',
        ),
        migrations.AddField(
            model_name='payment',
            name='recipts',
            field=models.ManyToManyField(to='shop.recipt'),
        ),
    ]
