# Generated by Django 4.2.4 on 2024-01-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_recipt_active_recipt_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank',
        ),
        migrations.AddField(
            model_name='recipt',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.bank'),
        ),
    ]
