# Generated by Django 4.2.4 on 2024-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_payment_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_chart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_for_payment', 'Waiting for Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
