# Generated by Django 4.2.4 on 2024-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_chart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
