# Generated by Django 4.2.4 on 2024-07-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlemail', '0004_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='email_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
