# Generated by Django 4.2.4 on 2024-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='height',
            field=models.PositiveIntegerField(default=700),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='width',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
