# Generated by Django 4.2.4 on 2024-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_imagefile_height_imagefile_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
