# Generated by Django 4.2.4 on 2024-07-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language_registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='regis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regsiterdlanguge', to='webpage.language_registered'),
        ),
    ]
