# Generated by Django 4.2.4 on 2023-11-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='check_out_time',
        ),
    ]
