# Generated by Django 4.2.4 on 2024-06-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Project',
        ),
    ]
